# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tela_login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Tela_login(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        MainWindow.setStyleSheet("background-color: #4285f4;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(150, 90, 361, 51))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(139, 160, 381, 221))
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                 "border-radius: 5px;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.email = QtWidgets.QLineEdit(self.frame)
        self.email.setGeometry(QtCore.QRect(50, 30, 281, 31))
        self.email.setStyleSheet("border: 1px solid #000;\n"
                                 "border-radius: 5px;")
        self.email.setObjectName("email")
        self.senha = QtWidgets.QLineEdit(self.frame)
        self.senha.setGeometry(QtCore.QRect(50, 70, 281, 31))
        self.senha.setStyleSheet("border: 1px solid #000;\n"
                                 "border-radius: 5px;")
        self.senha.setEchoMode(QtWidgets.QLineEdit.Password)
        self.senha.setObjectName("senha")
        self.btn_login = QtWidgets.QPushButton(self.frame)
        self.btn_login.setGeometry(QtCore.QRect(50, 110, 281, 31))
        self.btn_login.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_login.setStyleSheet("QPushButton{\n"
                                     "    background-color: #5B8DDE;\n"
                                     "   color: #FFF;\n"
                                     "}\n"
                                     "\n"
                                     "QPushButton:hover{\n"
                                     "    background-color: #1D52A8;\n"
                                     "}\n"
                                     "")
        self.btn_login.setObjectName("btn_login")
        self.btn_sair = QtWidgets.QPushButton(self.frame)
        self.btn_sair.setGeometry(QtCore.QRect(50, 150, 281, 31))
        self.btn_sair.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_sair.setStyleSheet("QPushButton{\n"
                                    "    background-color: RED;\n"
                                    "   color: #FFF;\n"
                                    "}\n"
                                    "\n"
                                    "QPushButton:hover{\n"
                                    "    background-color: #1D52A8;\n"
                                    "}\n"
                                    "")
        self.btn_sair.setObjectName("btn_sair")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate(
            "MainWindow", "Sinfor: Vacinas - Covid-19"))
        self.email.setPlaceholderText(_translate("MainWindow", "E-mail"))
        self.senha.setPlaceholderText(_translate("MainWindow", "Senha"))
        self.btn_login.setText(_translate("MainWindow", "Login"))
        self.btn_sair.setText(_translate("MainWindow", "Sair"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Tela_login()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
